# Generated by Django 5.1.3 on 2024-11-25 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_receita', models.IntegerField(unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('titulo_traduzido', models.CharField(blank=True, max_length=255, null=True)),
                ('imagem', models.URLField(blank=True, max_length=500, null=True)),
                ('tempo_preparo', models.IntegerField(blank=True, null=True)),
                ('tempo_total', models.IntegerField(blank=True, null=True)),
                ('porcoes', models.IntegerField(blank=True, null=True)),
                ('dificuldade', models.CharField(blank=True, max_length=50, null=True)),
                ('dicas', models.TextField(blank=True, null=True)),
                ('dicas_traduzidas', models.TextField(blank=True, null=True)),
                ('instrucoes', models.TextField(blank=True, null=True)),
                ('instrucoes_traduzidas', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='(00) 00000-0000', max_length=15),
        ),
        migrations.CreateModel(
            name='IngredienteReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_traduzido', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.FloatField(blank=True, null=True)),
                ('unidade', models.CharField(blank=True, max_length=50, null=True)),
                ('unidade_traduzida', models.CharField(blank=True, max_length=50, null=True)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='core.receita')),
            ],
        ),
    ]
